INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('1', 'Ben', 'Affleck', 'benaffleck@gmail.com', '../static/user_pics/ben_affleck_big.jpg', '../static/user_pics/ben_affleck_avatar.jpg', 'male', '123qwe', '2021-01-01', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('2', 'Matthew', 'McConaughey', 'matthew@gmail.com', '../static/user_pics/matthew_mc_conaughey_big.jpg', '../static/user_pics/matthew_mc_conaughey_avatar.jpg', 'male', '123qwe', '2021-02-02', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('3', 'Jim', 'Carrey', 'jim@gmail.com', '../static/user_pics/jim_carrey_big.jpg', '../static/user_pics/jim_carrey_avatar.jpg', 'male', '123qwe', '2021-02-03', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('4', 'Alessandra', 'Ambrosio', 'aless@gmail.com', '../static/user_pics/alessandra_ambrosio_big.jpg', '../static/user_pics/alessandra_ambrosio_avatar.jpg', 'female', '123qwe', '2021-02-04', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('5', 'Miranda', 'Kerr', 'mira@gmail.com', '../static/user_pics/miranda_kerr_big.jpg', '../static/user_pics/miranda_kerr_avatar.jpg', 'female', '123qwe', '2021-02-05', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('6', 'Gisele', 'Bündchen', 'gisele@gmail.com', '../static/user_pics/gisele_bundchen_big.jpg', '../static/user_pics/gisele_bundchen_avatar.jpg', 'female', '123qwe', '2021-02-06', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('7', 'Natalia', 'Vodianova', 'nata@gmail.com', '../static/user_pics/nataliya_vodyanova_big.jpg', '../static/user_pics/nataliya_vodyanova_avatar.jpg', 'female', '123qwe', '2021-02-06', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('8', 'Joan', 'Smalls', 'joan@gmail.com', '../static/user_pics/joan_smalls_big.jpg', '../static/user_pics/joan_smalls_avatar.jpg', 'female', '123qwe', '2021-01-07', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('9', 'Candice', 'Swanepoel', 'swanepoel@gmail.com', '../static/user_pics/candice_swanepoel_big.jpg', '../static/user_pics/candice_swanepoel_avatar.jpg', 'female', '123qwe', '2021-01-07', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('10', 'Karlie', 'Kloss', 'karlie@gmail.com', '../static/user_pics/karlie_kloss_big.jpg', '../static/user_pics/karlie_kloss_avatar.jpg', 'female', '123qwe', '2021-01-17', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('11', 'Carolyn', 'Murphy', 'carolyn@gmail.com', '../static/user_pics/carolyn_murphy_big.jpg', '../static/user_pics/carolyn_murphy_avatar.jpg', 'female', '123qwe', '2021-01-26', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('12', 'Liu', 'Wen', 'liu@gmail.com', '../static/user_pics/liu_wen_big.jpg', '../static/user_pics/liu_wen_avatar.jpg', 'female', '123qwe', '2021-01-13', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('13', 'Daria', 'Verbova', 'di@gmail.com', '../static/user_pics/daria_verbova_big.jpg', '../static/user_pics/daria_verbova_avatar.jpg', 'female', '123qwe', '2021-01-23', 'model');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('14', 'Johnny', 'Depp', 'jd@gmail.com', '../static/user_pics/johnny_depp_big.jpg', '../static/user_pics/johnny_depp_avatar.jpg', 'male', '123qwe', '2021-02-05', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('15', 'Leonardo', 'DiCaprio', 'leodi@gmail.com', '../static/user_pics/leonardo_dicaprio_big.jpg', '../static/user_pics/leonardo_dicaprio_avatar.jpg', 'male', '123qwe', '2021-02-08', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('16', 'Benedict', 'Cumberbatch', 'benedict@gmail.com', '../static/user_pics/benedict_cumberbatch_big.jpg', '../static/user_pics/benedict_cumberbatch_avatar.jpg', 'male', '123qwe', '2021-02-10', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('17', 'Adriano', 'Celentano', 'celentano@gmail.com', '../static/user_pics/adriano_celentano_big.jpg', '../static/user_pics/adriano_celentano_avatar.jpg', 'male', '123qwe', '2021-01-10', 'actor');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('18', 'Mykhailo', 'Khoma', 'dzi@gmail.com', '../static/user_pics/mykhailo_khoma_big.jpg', '../static/user_pics/mykhailo_khoma_avatar.jpg', 'male', '123qwe', '2021-01-11', 'musician');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('19', 'Elon', 'Musk', 'elon@gmail.com', '../static/user_pics/elon_musk_big.jpg', '../static/user_pics/elon_musk_avatar.jpg', 'male', '123qwe', '2021-01-11', 'CEO of Tesla');
INSERT INTO `tinder`.`users` (`user_id`, `first_name`, `last_name`, `email`, `pic_url`, `pic_url_avatar`, `gender`, `password`, `last_login_date`, `occupation`) VALUES ('20', 'Robert', 'Downey Jr', 'robjr@gmail.com', '../static/user_pics/robert_downey_jr_big.jpg', '../static/user_pics/robert_downey_jr_avatar.jpg', 'male', '123qwe', '2021-01-13', 'actor');


